[project]
name = "android-device-mcp"
version = "0.1.0"
description = "Android device MCP tools"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.12.4",
    "pillow>=11.3.0",
    "pydantic>=2.11.7",
]
